//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgiay_NTDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA_SAN_PHAM
    {
        public int ReviewID { get; set; }
        public int ProductID { get; set; }
        public int customerID { get; set; }
        public Nullable<int> Diem_danh_gia { get; set; }
        public string Nhan_xet { get; set; }
        public System.DateTime Ngay_danh_gia { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}
