//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webgiay_NTDH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.DANH_GIA_SAN_PHAM = new HashSet<DANH_GIA_SAN_PHAM>();
        }
    
        public int ProductID { get; set; }
        public string Ten_san_pham { get; set; }
        public string Mo_ta { get; set; }
        public Nullable<int> So_luong_ton_kho { get; set; }
        public string Thuong_hieu { get; set; }
        public string Hinh_anh { get; set; }
        public string Mau { get; set; }
        public string Kich_thuoc { get; set; }
        public decimal Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA_SAN_PHAM> DANH_GIA_SAN_PHAM { get; set; }
    }
}
